// <auto-generated />
using System;
using BTLQuanLy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BTLQuanLy.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231114143943_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BTLQuanLy.Models.DonVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DonViId")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiDonViId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGiaiTan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhLap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSua")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TenDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.HasIndex("LoaiDonViId");

                    b.ToTable("DonVis");
                });

            modelBuilder.Entity("BTLQuanLy.Models.HocVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DonViId")
                        .HasColumnType("int");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("MaHocVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSua")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHocVien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("BTLQuanLy.Models.LoaiDonVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSua")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiDv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiDonVis");
                });

            modelBuilder.Entity("BTLQuanLy.Models.DonVi", b =>
                {
                    b.HasOne("BTLQuanLy.Models.DonVi", null)
                        .WithMany("DonVis")
                        .HasForeignKey("DonViId");

                    b.HasOne("BTLQuanLy.Models.LoaiDonVi", "LoaiDonVi")
                        .WithMany()
                        .HasForeignKey("LoaiDonViId");

                    b.Navigation("LoaiDonVi");
                });

            modelBuilder.Entity("BTLQuanLy.Models.HocVien", b =>
                {
                    b.HasOne("BTLQuanLy.Models.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId");

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("BTLQuanLy.Models.DonVi", b =>
                {
                    b.Navigation("DonVis");
                });
#pragma warning restore 612, 618
        }
    }
}
